// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxkrJl2R49iktFXUYyReSwMd-KKEdJZ8w',
    appId: '1:491619971507:web:e0c77254d82c5304261bc6',
    messagingSenderId: '491619971507',
    projectId: 'naliv-web',
    authDomain: 'naliv-web.firebaseapp.com',
    storageBucket: 'naliv-web.firebasestorage.app',
    measurementId: 'G-GG63GW9EFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2v2JMjQ0kBEIeQnpWmtaiTodrIa4WYKM',
    appId: '1:491619971507:android:ead0a8a0a86dc317261bc6',
    messagingSenderId: '491619971507',
    projectId: 'naliv-web',
    storageBucket: 'naliv-web.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMDLSkReT13fTycu29GB81zXZoYBpUN-c',
    appId: '1:491619971507:ios:b473b07db03c8f27261bc6',
    messagingSenderId: '491619971507',
    projectId: 'naliv-web',
    storageBucket: 'naliv-web.firebasestorage.app',
    iosBundleId: 'com.example.nalivDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMDLSkReT13fTycu29GB81zXZoYBpUN-c',
    appId: '1:491619971507:ios:b473b07db03c8f27261bc6',
    messagingSenderId: '491619971507',
    projectId: 'naliv-web',
    storageBucket: 'naliv-web.firebasestorage.app',
    iosBundleId: 'com.example.nalivDelivery',
  );
}
