// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCWJN5-ik7w6VdVMB9c-EZmQKRYyyxEgw',
    appId: '1:708777510505:web:1bafdcd9c3dd0a00b604f8',
    messagingSenderId: '708777510505',
    projectId: 'naliv-web-test',
    authDomain: 'naliv-web-test.firebaseapp.com',
    storageBucket: 'naliv-web-test.firebasestorage.app',
    measurementId: 'G-PRQBG0PR9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn1w3e9fb565XeT33bXH_KOVdbpbaP8Zs',
    appId: '1:708777510505:android:617d39b5a388808bb604f8',
    messagingSenderId: '708777510505',
    projectId: 'naliv-web-test',
    storageBucket: 'naliv-web-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHvlpxuQSW4ZWE3XHg3vhvYfBvK0eeNLM',
    appId: '1:708777510505:ios:1ddb1b587f99a39eb604f8',
    messagingSenderId: '708777510505',
    projectId: 'naliv-web-test',
    storageBucket: 'naliv-web-test.firebasestorage.app',
    iosBundleId: 'naliv_delivery',
  );
}
